# Generated by Django 3.0.5 on 2020-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('salary', models.FloatField(null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('amount_of_jobs', models.IntegerField()),
                ('contact', models.EmailField(max_length=254)),
                ('type_of_job', models.CharField(choices=[('fixed', 'Work routine will be mostly done in office or company headquarters'), ('remote', 'Work routine will be mostly done home-office ')], max_length=10)),
                ('technologies', models.ManyToManyField(to='api.Technology')),
            ],
        ),
    ]
